development:
  base_uri: https://10.10.2.31/TEST
  verify: false
  username: admin
  password: inf24!sp

test:
  base_uri: https://10.10.2.31/TEST
  verify: false
  username: admin
  password: inf24!sp