development:
  host: 10.10.2.31
  protocol: https
  https_verify: false
  path: /TEST
  username: admin
  password: inf24!sp

test:
  host: 10.10.2.31
  path: /TEST
  protocol: https
  https_verify: false
  username: admin
  password: inf24!sp

production:
  host: 10.10.2.31
  protocol: https
  https_verify: false
  path: /BGU
  username: admin
  password: inf24!sp
