development:
  host: 172.30.5.1
  base: dc=adm,dc=local
  bind_dn: cn=administrator,cn=Users,dc=adm,dc=local
  password: Rob!ng00d

test:
  host: 172.30.5.1
  base: dc=adm,dc=local
  bind_dn: cn=administrator,cn=Users,dc=adm,dc=local
  password: Rob!ng00d

production:
  host: 172.30.5.1
  base: dc=adm,dc=local
  bind_dn: cn=administrator,cn=Users,dc=adm,dc=local
  password: Rob!ng00d

