ImportAssetsFrom1cJob:
  cron: "0 0 * * 1-5"
  queue: sheduler

ImportMaterialsFrom1cJob:
  cron: "0 0 * * 1-5"
  queue: sheduler

ImportEmployeesJob:
  cron: "0 10,13,16,19 * * 1-5"
  queue: sheduler